### PR TITLE
Support for Laravel Blade.

### PR DESCRIPTION
**Pull request by MattiasMediaempire**
Added a modifier for support with Laravel Blade since tags are only available in Antlers. Also updated the readme.

### CODE REVIEW

**Comment by edcs** [comment]
This looks good! Thanks for contributing too 😄

Does it obsolete `LaravelMixTags` (https://github.com/edcs/laravel-mix-statamic/blob/master/LaravelMixTags.php) or does it provide Blade syntax alongside Antlers? If it's the latter then it would be good to move the shared functionality into an abstract class which is extended by `LaravelMixTags` and `LaravelMixModifier`.

**Comment by MattiasMediaempire** [comment]
@edcs Pleasure is all mine! 

The modifier would work both with Antlers and with Laravel Blade, however that would be a breaking change since the syntax in the template is different. Providing both options might be a good idea. I'll extract the shared functionality and send up a new PR as soon as I can :)

**Comment by edcs** [comment]
Awesome! Feel free to push the changes into the branch you created for this PR and I'll re-review 👍

**Comment by MattiasMediaempire** [comment]
@edcs Noticed a bug causing the asset url output to fail when visiting a different locale (for example /se). Do you want me to push the fix to this branch or create a different one?

**Comment by MattiasMediaempire** [comment]
@edcs Any update on this?

**Pull request merged**
